steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/tss-01-268104/tss-flask-restful-api', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/tss-01-268104/tss-flask-restful-api']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'tss-ser-01', '--image', 'gcr.io/tss-01-268104/tss-flask-restful-api', '--region', 'asia-east1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/tss-01-268104/tss-flask-restful-api

